### ISSUE TITLE
KANBAN Board Setup

### ISSUE THREAD

**Issue by badger-99** [badger-99/ruby_group_capstone#30]
### There are three members in our team for the Ruby Group Capstone Project
- Team member 1 -> @malikhaiderkhan
- Team member 2 -> @badger-99
- Team member 3 -> @devendra-alt

**Comment by julie-ify** [comment]
Hi @badger-99, @malikhaiderkhan and @devendra-alt, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly include the link to the Kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by topeogunleye** [comment]
Hi Team 👋, 

Your project is complete!  You've done great in implementing this Kanban board. 🎊 
Congratulations! 🎉 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 

### 🏆 **Project Highlights:**
1. **Accurate GitHub Issue Submission:**🌐
   
2. **Precise Kanban Board Structure:**

3. **Descriptive and Detailed Cards:**🎯
   
4. **Fair Distribution of Tasks:**

5. **Full Assignment of Cards:**

Happy Coding! 🌟

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
